# Generated by Django 4.2.2 on 2023-06-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='session',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='Morning', max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='course',
            field=models.CharField(choices=[('Python', 'Python3'), ('Java', 'Java 8'), ('Web Designing', 'Web Designing'), ('Django', 'Django'), ('Full Stack', 'Full Stack')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, verbose_name='Email id'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(help_text='Name should be within 30 letters', max_length=30, verbose_name='Enter Name'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.IntegerField(help_text='Phone Number should contain 10 digits', verbose_name='Phone Number'),
        ),
    ]
