# Generated by Django 4.2.2 on 2023-06-28 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_enquiry_date_alter_enquiry_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdId', models.CharField(max_length=10)),
                ('stdName', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('course', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C', 'C'), ('C++', 'C++'), ('Django', 'Django'), ('Full Stack', 'Full Stack')], default='Python', max_length=25)),
                ('joiningDate', models.DateField()),
                ('fees', models.IntegerField()),
                ('status', models.CharField(choices=[('Yet to Start', 'Yet to Start'), ('Started', 'Started'), ('Hold', 'Hold'), ('Discontinued', 'Discontinued'), ('Completed', 'Completed')], max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 18, 0, 34, 184812)),
        ),
    ]
