# Generated by Django 4.2.2 on 2023-06-28 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_student_alter_enquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='Chennai'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 18, 12, 40, 102492)),
        ),
        migrations.AlterField(
            model_name='student',
            name='stdId',
            field=models.CharField(max_length=10, verbose_name='Student Id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stdName',
            field=models.CharField(max_length=30, verbose_name='Student Name'),
        ),
    ]
