# Generated by Django 4.2.2 on 2023-07-05 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_address_alter_enquiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 17, 44, 29, 295936)),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(),
        ),
    ]
